### ISSUE TITLE
refactor: use standard Helm templating

### ISSUE THREAD

**Issue by justinthelaw** [defenseunicorns/leapfrogai-ui#110]
**Describe the Feature**

Currently, the UI uses direct Zarf variable replacement within its charts instead of the standard Helm values replacement pattern. Refactor the existing charts to take on a Helm templating pattern with a values file that isolates the Zarf ENV variable replacement instead.

**Additional context**

See [leapfrogai-model-skeleton](https://github.com/defenseunicorns/leapfrog-model-skeleton/tree/main/chart) or [leapfrogai-api](https://github.com/defenseunicorns/leapfrogai-api/tree/main/chart) for examples.

**Comment by YrrepNoj** [comment]
Related to #107

**Comment by lemonprogis** [comment]
I don't mind to pick this up if that's cool with y'all?
