### ISSUE TITLE
fix: summarization endpoint and ENV

### ISSUE THREAD

**Issue by justinthelaw** [defenseunicorns/leapfrogai-ui#153]
**Describe the Feature**

1. Use the `chat/completions` endpoint for summarization
2. Swap default to `vllm` for default chat and summarization model
3. Fix the summarization system prompts in the Zarf YAMl and Helm charts to be consistent and properly named

**Additional context**

See this divergent branch for implementation details: https://github.com/defenseunicorns/leapfrogai-ui/tree/pre-uds-fixes

**Comment by gphorvath** [comment]
@justinthelaw ahhhh, this is partially done. We fixed completions in #158
